[tool.poetry]
name = "pythonp"
version = "0.1.0"
description = ""
authors = ["saad-pixel <marva.saad2@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^1.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
